# Generated by Django 5.0.7 on 2024-07-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="quote",
            name="author",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="quote",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
